//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeralFlagTasks {
            get {
                return ((bool)(this["GeralFlagTasks"]));
            }
            set {
                this["GeralFlagTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeralFlagClocker {
            get {
                return ((bool)(this["GeralFlagClocker"]));
            }
            set {
                this["GeralFlagClocker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeralFlagBackup {
            get {
                return ((bool)(this["GeralFlagBackup"]));
            }
            set {
                this["GeralFlagBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\Infinite\\Janitor\\bin\\backup_diario.bat")]
        public string GeralPathBackup {
            get {
                return ((string)(this["GeralPathBackup"]));
            }
            set {
                this["GeralPathBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime GeralLastBackup {
            get {
                return ((global::System.DateTime)(this["GeralLastBackup"]));
            }
            set {
                this["GeralLastBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\Infinite\\Janitor\\bin\\check_tarefas.bat")]
        public string GeralCheckProgram {
            get {
                return ((string)(this["GeralCheckProgram"]));
            }
            set {
                this["GeralCheckProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MT5FlagProgram {
            get {
                return ((bool)(this["MT5FlagProgram"]));
            }
            set {
                this["MT5FlagProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MT5FlagNotClose {
            get {
                return ((bool)(this["MT5FlagNotClose"]));
            }
            set {
                this["MT5FlagNotClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\B3\\MetaTrader 5\\terminal64.exe")]
        public string MT5PathGenial {
            get {
                return ((string)(this["MT5PathGenial"]));
            }
            set {
                this["MT5PathGenial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\B3\\ModalMais MetaTrader 5\\terminal64.exe")]
        public string MT5PathModal {
            get {
                return ((string)(this["MT5PathModal"]));
            }
            set {
                this["MT5PathModal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\B3\\XM Global MT5\\terminal64.exe")]
        public string MT5PathXmglob {
            get {
                return ((string)(this["MT5PathXmglob"]));
            }
            set {
                this["MT5PathXmglob"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColetFlagProgram {
            get {
                return ((bool)(this["ColetFlagProgram"]));
            }
            set {
                this["ColetFlagProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\Infinite\\Colethon\\bin\\startup.bat")]
        public string ColetPathProgram {
            get {
                return ((string)(this["ColetPathProgram"]));
            }
            set {
                this["ColetPathProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\BLACK\\Publico\\")]
        public string ColetPathShared {
            get {
                return ((string)(this["ColetPathShared"]));
            }
            set {
                this["ColetPathShared"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ColetLastExecute {
            get {
                return ((global::System.DateTime)(this["ColetLastExecute"]));
            }
            set {
                this["ColetLastExecute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LotoFlagProgram {
            get {
                return ((bool)(this["LotoFlagProgram"]));
            }
            set {
                this["LotoFlagProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\Infinite\\Lothon\\bin\\palpites.bat")]
        public string LotoPathProgram {
            get {
                return ((string)(this["LotoPathProgram"]));
            }
            set {
                this["LotoPathProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\Infinite\\Lothon\\data\\safeToDelete.tmp")]
        public string LotoPathSignal {
            get {
                return ((string)(this["LotoPathSignal"]));
            }
            set {
                this["LotoPathSignal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LotoLastExecute {
            get {
                return ((global::System.DateTime)(this["LotoLastExecute"]));
            }
            set {
                this["LotoLastExecute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuantFlagProgram {
            get {
                return ((bool)(this["QuantFlagProgram"]));
            }
            set {
                this["QuantFlagProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\Infinite\\Quanthon\\bin\\startup.bat")]
        public string QuantPathProgram {
            get {
                return ((string)(this["QuantPathProgram"]));
            }
            set {
                this["QuantPathProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Apps\\Infinite\\Quanthon\\data\\safeToDelete.tmp")]
        public string QuantPathSignal {
            get {
                return ((string)(this["QuantPathSignal"]));
            }
            set {
                this["QuantPathSignal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime QuantLastExecute {
            get {
                return ((global::System.DateTime)(this["QuantLastExecute"]));
            }
            set {
                this["QuantLastExecute"] = value;
            }
        }
    }
}
